-- MySQL Script generated by MySQL Workbench
-- Sat Feb  9 17:52:40 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ds` DEFAULT CHARACTER SET utf8 ;
USE `ds` ;

-- -----------------------------------------------------
-- Table `mydb`.`trace_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ds`.`trace_manager` (
  `mng_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `mng_name` VARCHAR(45) NOT NULL,
  `login_name` VARCHAR(45) NOT NULL,
  `login_password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(200) NULL,
  `phone` VARCHAR(200) NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `valued` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`mng_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trace_access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ds`.`trace_access` (
  `trace_access_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `trace_manager_id` BIGINT(20) NOT NULL,
  `shop_id` BIGINT(20) NULL,
  `cid` BIGINT(20) NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `valued` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`trace_access_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
